# (from: https://github.com/codecov/example-node/blob/master/.travis.yml)
language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "4.1"
  - "4.0"
install:
  - npm install
script:
  - npm test
